Import('env') 

env['LIBS'].insert(0, 'epi')

performance_programs = []
performance_programs += env.Program(target='ei_performance', source = 'ei_performance.cpp')

Alias('check', performance_programs)
